os: linux
dist: trusty
cache:
  directories:
    - cachedir

jobs:
  include:
  - stage: stage 1    
    script:
    - wget https://github.com/kr15h/openframeworks-rpi-image/releases/download/v1.0.3/raspbian_lite-2017-07-05-of_v0.10.0.img.zip
    - mv ./*.zip ./cachedir
  - stage: stage 2
    script:
    - ls -l
    - rm -rf cachedir
  - stage: stage 3
    script:
    - ls -l
    - cd cachedir
    - ls -l
